discovery:
  image: "discovery:0.0.1-SNAPSHOT"
  hostname: discovery
  ports:
  - "8761:8761"
config:
  image: "config:0.0.1-SNAPSHOT"
  hostname: config
  links:
  - discovery
  environment:
     EUREKA_HOST: discovery
     EUREKA_PORT: 8761

person:
  image: person:0.0.1-SNAPSHOT
  hostname: person
  links:
     - discovery
     - config
  environment:
     EUREKA_HOST: discovery
     EUREKA_PROT: 8761
     SPRING_PROFILES_ACTIVE: docker
some:
  image: some:0.0.1-SNAPSHOT
  hostname:  some
  links:
    - discovery
    - config
  environment:
     EUREKA_HOST: discovery
     EUREKA_PROT: 8761
     SPRING_PROFILES_ACTIVE: docker
ui:
  image: ui:0.0.1-SNAPSHOT
  hostname: ui
  links:
      - discovery
      - config
      - person
      - some
  environment:
     EUREKA_HOST: discovery
     EUREKA_PROT: 8761
     SPRING_PROFILES_ACTIVE: docker
  ports:
      - "80:80"
monitor:
  image: monitor:0.0.1-SNAPSHOT
  hostname: monitor
  links:
    - discovery
    - config
    - person
    - some
    - ui
  environment:
     EUREKA_HOST: discovery
     EUREKA_PROT: 8761
     SPRING_PROFILES_ACTIVE: docker
#  ports:
#    - "8989:8989"